GET http://localhost:3001/api/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwOTNlZGYyODZjNTQ3NWM3YzVhZjlkMCIsImlhdCI6MTYyMDQ3MDU5NywiZXhwIjoxNjIwNDcwODk3fQ.Scsu6YlsN4F4b5lYMbucFFpZoFsQGrqb49FkOaDR-rI
###
GET http://localhost:3001/api/user/userInfo
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwOTNlZGYyODZjNTQ3NWM3YzVhZjlkMCIsImlhdCI6MTYyMTE2MzAwNCwiZXhwIjoxNjIxMTYzMzA0fQ.DQAdjJygNzE_vs9pzinIxoXEwK2h68uSs8kXLXsLy3o

###
POST http://localhost:4001/api/auth/token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwOTNlZGYyODZjNTQ3NWM3YzVhZjlkMCIsImlhdCI6MTYyMTE2MjYxMX0.6JKSraTIyCgOqVh5cbgYju4h89wGxGDhIT7LnZeIsFo"
}



###
DELETE http://localhost:4001/api/auth/logout
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwOTNlZGYyODZjNTQ3NWM3YzVhZjlkMCIsImlhdCI6MTYyMTE2MjYxMX0.6JKSraTIyCgOqVh5cbgYju4h89wGxGDhIT7LnZeIsFo"
}

###
POST http://localhost:4001/login
Content-Type: application/json

{
    "email": "kekek@email.com",
    "password": "1234567"
}



###
POST http://localhost:4001/api/auth/register
Content-Type: application/json

{
    "name": "username",
    "email": "u2@user.com",
    "password": "1234567"
}

###
POST http://localhost:4001/api/auth/login
Content-Type: application/json

{
    "email": "u1@user.com",
    "password": "1234567"
}

###
###########################################################################################
###
POST http://localhost:4001/register
Content-Type: application/json

{
    "name": "username",
    "email": "u123@email.com",
    "password": "1234567"
}


###
POST http://localhost:3001/api/user/login
Content-Type: application/json

{
    "email": "kekek@email.com",
    "password": "1234567"
}

###
GET http://localhost:4002/test
Content-Type: application/json

