GET http://localhost:3001/api/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MjAzMTk3MjYsImV4cCI6MTYyMDMyMDAyNn0.1VXeNfAnpWJKSJhL4xcmCC5Jop9LZ5FMwoJMQNn6-BQ
###
GET http://localhost:3001/api/user/userInfo
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwODFkZDBiZmYwMzk3MTk0NGQzNGU5NiIsImlhdCI6MTYyMDMyMTMzMiwiZXhwIjoxNjIwMzIxNjMyfQ.tXf27OUQF7HoAXuyeF4OHBX5Alq_T1itUZkR4bnBTrk

###
POST http://localhost:4001/token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDgxZGQwYmZmMDM5NzE5NDRkMzRlOTYiLCJpYXQiOjE2MjAzMTQzMjN9.VBXqbLw8fV9JFkYXEhtmVkUxq5VGnK_FVltM8BBlKag"
}



###
DELETE http://localhost:4001/logout
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDgxZGQwYmZmMDM5NzE5NDRkMzRlOTYiLCJpYXQiOjE2MjAzMTYxMTR9.5Y69I_W8lKDhFWcErnjE2gcMNPQjKmDt27N2m6WQ-RI"
}

###
POST http://localhost:4001/login
Content-Type: application/json

{
    "email": "kekek@email.com",
    "password": "1234567"
}



###
POST http://localhost:4001/register
Content-Type: application/json

{
    "name": "username",
    "email": "u1@user.com",
    "password": "1234567"
}

###
POST http://localhost:4001/login
Content-Type: application/json

{
    "email": "u1@user.com",
    "password": "1234567"
}

###
###########################################################################################
###
POST http://localhost:4001/register
Content-Type: application/json

{
    "name": "username",
    "email": "u123@email.com",
    "password": "1234567"
}


###
POST http://localhost:3001/api/user/login
Content-Type: application/json

{
    "email": "kekek@email.com",
    "password": "1234567"
}