GET http://localhost:3001/api/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwOTNlZGYyODZjNTQ3NWM3YzVhZjlkMCIsImlhdCI6MTYyMDQ3MDU5NywiZXhwIjoxNjIwNDcwODk3fQ.Scsu6YlsN4F4b5lYMbucFFpZoFsQGrqb49FkOaDR-rI
###
GET http://localhost:3001/api/user/userInfo
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwOTNlZGYyODZjNTQ3NWM3YzVhZjlkMCIsImlhdCI6MTYyMTE2MzAwNCwiZXhwIjoxNjIxMTYzMzA0fQ.DQAdjJygNzE_vs9pzinIxoXEwK2h68uSs8kXLXsLy3o

###
POST http://localhost:4001/api/auth/token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwOTNlZGYyODZjNTQ3NWM3YzVhZjlkMCIsImlhdCI6MTYyMTE2MjYxMX0.6JKSraTIyCgOqVh5cbgYju4h89wGxGDhIT7LnZeIsFo"
}



###
DELETE http://localhost:4001/api/auth/logout
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwOTNlZGYyODZjNTQ3NWM3YzVhZjlkMCIsImlhdCI6MTYyMTE2MjYxMX0.6JKSraTIyCgOqVh5cbgYju4h89wGxGDhIT7LnZeIsFo"
}

###
POST http://localhost:4001/login
Content-Type: application/json

{
    "email": "kekek@email.com",
    "password": "1234567"
}



###
POST http://localhost:4001/api/auth/register
Content-Type: application/json

{
    "name": "username",
    "email": "u2@user.com",
    "password": "1234567"
}

###
POST http://localhost:4001/api/auth/login
Content-Type: application/json

{
    "email": "u1@user.com",
    "password": "1234567"
}

###
###########################################################################################
###
POST http://localhost:4001/register
Content-Type: application/json

{
    "name": "username",
    "email": "u123@email.com",
    "password": "1234567"
}


###
POST http://localhost:3001/api/user/login
Content-Type: application/json

{
    "email": "kekek@email.com",
    "password": "1234567"
}

###
GET http://localhost:4002/test
Content-Type: application/json





###
DELETE http://localhost:4001/api/auth/logout
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwOTNlZGYyODZjNTQ3NWM3YzVhZjlkMCIsImlhdCI6MTYyNTE1NTA5M30.h-zzmkZRQYrRvHKAcYDDkkMAd8waL-kMW60O_7mr6WM"
}

#eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwOTNlZGYyODZjNTQ3NWM3YzVhZjlkMCIsImlhdCI6MTYyNTE1NTA5M30.h-zzmkZRQYrRvHKAcYDDkkMAd8waL-kMW60O_7mr6WM
#eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDkzZWRmMjg2YzU0NzVjN2M1YWY5ZDAiLCJpYXQiOjE2MjAzMTM3Njl9.5DMnbQtETu5zCKSS34TMfP5gklhLc_-PviP_mZGkMCo
#eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwOTNlZGYyODZjNTQ3NWM3YzVhZjlkMCIsImlhdCI6MTYyNTE1NTA5MywiZXhwIjoxNjI1MTU1MzkzfQ.VHFgkyY0Q4mXg2jyfBaafKwf-TvzzdX_6jPk408PuFQ


#
###
POST http://localhost:4001/api/auth/register
Content-Type: application/json

{
    "name": "user8",
    "email": "u9@user.com",
    "password": "1234567"
}

###
POST http://localhost:4001/api/auth/login
Content-Type: application/json

{
    "email": "u10@u.com",
    "password": "1234567"
}



### 
POST http://localhost:3001/api/user/update-profile/username HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwZTAyODNlZGNjOTk1MzExYzQyMzgwMyIsImlhdCI6MTYyNTMwNjk2OCwiZXhwIjoxNjI1MzA3MjY4fQ.XsNaX1I_FNHBJKvi_eHQzz9OU8ajlnGpY58mSrqXiB4

{
    "name": "user10",
    "userId": "60e0283edcc995311c423803"
}

###
<request>
    <name>user10</name>
</request>

###
POST http://localhost:4001/api/auth/register
Content-Type: application/json

{
    "name": "user12",
    "email": "u12@user.com",
    "password": "1234567"
}

###
POST http://localhost:4001/api/auth/login
Content-Type: application/json

{
    "email": "u12@user.com",
    "password": "1234567"
}


### 
POST http://localhost:3001/api/user/update-profile/email HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwZTJhYjQ5NmY1NjBlNzY3ODBiNDc5OCIsImlhdCI6MTYyNTQ2Nzc5MSwiZXhwIjoxNjI1NDY4MDkxfQ.7_sJNTf50P_lyjP6z-EE1c16ic-lNQnjbu-JMYkDtrg

{
    "email": "u12@u.com",
    "userId": "60e2ab496f560e76780b4798"
}